### PR TITLE
Update for tf2

### PR DESCRIPTION
**Pull request by nlimpert**
Adhere the changes to `tf2` in ROS Melodic.

### CODE REVIEW

**Comment by nlimpert** [comment]
@lyndwyrm666 could you maybe have a look at this?

**Comment by lyndwyrm666** [comment]
as in testing it?

**Comment by nlimpert** [comment]
Yes but in general if you consider there are issues with the change.

**Review by lyndwyrm666 — APPROVED** [review]
Looks good to me

**Comment by nlimpert** [comment]
Thanks for the review!

**Pull request merged**
